add help message for in-daemonset cilium CLI subcommands
cilium/cilium-cli pull request #1279
Opened 2022-12-08 06:53 UTC by kranurag7

Signed-off-by: Anurag <contact.anurag7@gmail.com>
- Print a message whenever in-daemonset CLI subcommads are called for. 
```bash
$ cilium bpf 
Exec into the daemonset to use this subcommand.
To exec into the daemonset use the following command:
kubectl exec -it -n kube-system ds/cilium -- bash
$ cilium help bpf 
Exec into the daemonset to use this subcommand.
To exec into the daemonset use the following command:
kubectl exec -it -n kube-system ds/cilium -- bash
```

Fixes #1229

2022-12-08 13:03 UTC, squeed commented on internal/cli/cmd/cmd.go
> +		Long: `Exec into the daemonset to use this subcommand.
Wording suggestion:
"This command is only available in the Cilium agent.
Exec in to a running cilium pod to use it.
kubectl exec -it -n kube-system ds/cilium -- bash`,

2022-12-08 13:03 UTC, squeed commented
Brilliant idea :-). Just one wording suggestion.

2022-12-08 13:04 UTC, squeed requested changes

2022-12-08 13:04 UTC, squeed commented on internal/cli/cmd/cmd.go
> +		Long: `Exec into the daemonset to use this subcommand.
Wording suggestion:
"This command is only available in the Cilium agent.
Exec in to a running cilium pod to use it.
kubectl exec -it -n kube-system ds/cilium -- bash`,

2022-12-14 04:23 UTC, kranurag7 commented on internal/cli/cmd/cmd.go
> +		Aliases: []string{"cleanup", "debuginfo", "endpoint", "fqdn", "identity", "ip", "kvstore", "lrp", "map", "metrics", "monitor", "node", "policy", "prefilter", "preflight", "recorder", "service"},
I agree, if there's a `-o list` or `--output list` flag that will list all the commands of per node cilium CLI then we can use that.

2023-05-05 21:57 UTC, joestringer commented
@tklauser @kranurag7 can we help move this PR forward? What's the next step?

2023-10-27 03:46 UTC, kranurag7 commented
@joestringer thanks for https://github.com/cilium/cilium/pull/28085 👍🏻 With that PR being merged, I think we can close this one. I'll still wait for any comments that need to be addressed w.r.t. this PR, but if not, then please feel free to close this pull request.

2023-10-27 16:00 UTC, joestringer commented
I think that this proposal may still provide some value, and potentially fits in future with the proposal from https://github.com/cilium/cilium-cli/issues/1930 . I'll defer to @tklauser and @michi-covalent whether they think it's worth trying to revisit this PR, rebase & get it into the tree.

As of now, the CI is reporting failures but I guess that's because it was from a while ago so if we wanted to merge this then it at least would need a rebase against the tip of the tree.  I'm not sure what the solution is for the help issue in the thread above, but I think that's a proposal for an extra change on top? We can always iterate and discuss on that in a subsequent follow-up PR.

2024-01-23 11:53 UTC, squeed commented
@kranurag7 It's been quite some time that this PR has sat; if it's still open in a week it's probably time to close.

Especially now that we've renamed cilium.

2024-01-23 12:00 UTC, kranurag7 commented
Hey @squeed 
I was waiting on other maintainers Joe maintained to have a look again. 
I think given the binary is already renamed it's safe to close this. 

I'll leave it upto you unless you or others have some comment left here. 
Thank you. :)

2024-01-23 22:45 UTC, joestringer commented
I think there's been plenty of time for the other folks to chime in and there's no sign of interest. Regardless, thank you @kranurag7 for your efforts investigating this and making the proposal.

2024-01-23 22:45 UTC, closed without merging