add ca.crt to LTS Secrets
cilium/cilium-cli pull request #145
Opened 2021-03-30 10:25 UTC by kaworu

This PR ensure that all the Secrets containing a TLS keypair are of `kubernetes.io/tls` type. This brings consistency with respect to how we generate certificates [with certgen](https://github.com/cilium/certgen/blob/d9f612a4775d85632acfa9653cade50e1cd2af50/internal/generate/generate.go#L147) and [Helm](https://github.com/cilium/cilium/blob/de8b14eb7816b773ec757ef0847dcfff56d507d2/install/kubernetes/cilium/templates/hubble-server-secret.yaml#L10).

Besides honoring the required `tls.key` and `tls.crt` keys, we also consistently add `ca.crt` to theses Secrets (see https://github.com/cilium/cilium/pull/15443 for context).

Finally, use the newly added `ca.crt` for both Hubble and Relay. This allow compatibility with [cert-manager](https://cert-manager.io/).

After this PR we could consider a `--generate-certificates=false` flag preventing certificate generation from the CLI. Users could then use cert-manager go generate the TLS Secrets since the deployments are using the TLS Secrets in a compatible way.

2021-03-30 12:03 UTC, rolinh approved these changes
LGTM :rocket: 

EDIT: the go check failure looks legit (doc update required).

2021-03-30 12:20 UTC, kaworu commented
Marking as draft until https://github.com/cilium/cilium/pull/15443 is merged, but this PR is ready for review.

2021-03-31 18:52 UTC, jrajahalme requested changes
CA crt name used here is `ca.key`, no the intended `ca.crt`.

2021-04-01 09:08 UTC, kaworu commented on clustermesh/certs.go
> +		defaults.CASecretKeyName: k.certManager.CACertBytes(),
Yes you are correct, thank you good catch!

2021-04-13 16:07 UTC, kaworu commented
Marking as ready to review as https://github.com/cilium/cilium/pull/15443 has been merged.

2021-04-30 08:38 UTC, tgraf approved these changes

2021-04-30 08:38 UTC, merged

2021-04-30 10:39 UTC, tklauser commented
This PR seems to break installation of Cilium on `kind` (maybe others). When using `cilium install` on a `kind` cluster with 2 nodes the installation gets stuck at:

```
cilium install
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.10.0"
ℹ️  Cilium version not set, using default version "v1.9.6"
🔮 Auto-detected cluster name: kind-kind
🔮 Auto-detected IPAM mode: kubernetes
🔮 Auto-detected datapath mode: tunnel
🔑 Generating CA...
2021/04/30 12:32:41 [INFO] generate received request
2021/04/30 12:32:41 [INFO] received CSR
2021/04/30 12:32:41 [INFO] generating key: ecdsa-256
2021/04/30 12:32:41 [INFO] encoded CSR
2021/04/30 12:32:41 [INFO] signed certificate with serial number 341950654555647912224012010248856335904663509460
🔑 Generating certificates for Hubble...
2021/04/30 12:32:41 [INFO] generate received request
2021/04/30 12:32:41 [INFO] received CSR
2021/04/30 12:32:41 [INFO] generating key: ecdsa-256
2021/04/30 12:32:41 [INFO] encoded CSR
2021/04/30 12:32:41 [INFO] signed certificate with serial number 650073862086065741661726551118996732934131520777
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed...
```

Until it eventually times out. The Cilium pods seem stuck in `Init` state with `kubectl -n kube-system describe pod ...` showing:

```
[...]
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    94s                default-scheduler  Successfully assigned kube-system/cilium-9mkxv to kind-control-plane
  Warning  FailedMount  30s (x8 over 94s)  kubelet            MountVolume.SetUp failed for volume "hubble-tls" : references non-existent secret key: ca.crt
```

Not sure whether that's related. CI also seems to fail on `kind` for latest `master`.

/cc @kaworu @tgraf

2021-04-30 11:42 UTC, kaworu commented
@tklauser I've missed one instance [reported by @jrajahalme](https://github.com/cilium/cilium-cli/pull/145#pullrequestreview-625614573) during the review, thank you for reporting this! Can you try https://github.com/cilium/cilium-cli/pull/200 please?

2021-04-30 13:40 UTC, tklauser commented
Thanks @kaworu, works fine in my local tests.