sysdump: Collect node init Pod logs and DaemonSet
cilium/cilium-cli pull request #1754
Opened 2023-06-23 09:03 UTC by ioandr

Closes #1192

2023-07-06 19:06 UTC, derailed requested changes
Thank you for this PR! Just a couple picks...

2023-07-06 19:15 UTC, ioandr commented on sysdump/sysdump.go
> +					return fmt.Errorf("failed to collect the Cilium Node Init daemonset: %w", err)
I followed the convention that the rest of the tasks follow, that is, use the same error for both cases.

Still, I agree with your comment so let me push a small FIXUP for this.

2023-07-10 22:33 UTC, michi-covalent approved these changes

2023-07-12 11:54 UTC, tklauser approved these changes

2023-07-12 11:54 UTC, merged