Expand warning about big sysdump
cilium/cilium-cli pull request #1799
Opened 2023-07-05 11:32 UTC by nebril

fixes: https://github.com/cilium/cilium-cli/issues/1371

2023-07-07 14:28 UTC, derailed requested changes
@nebril LGTM - small pick... I think it would be good to show what we consider large ie 20 nodes + the current settings for the logs configs ie limit and since to make users aware of these settings. 
Interestingly 19 nodes running for ~1 year with current defaults could dump ~19Gib worth of agent logs with no warnings...

2023-07-13 18:57 UTC, nebril commented
Forgot to re-push :facepalm:

2023-07-21 22:35 UTC, christarazi approved these changes

2023-08-11 14:43 UTC, derailed approved these changes
LGTM

2023-08-14 17:51 UTC, merged