ci: Add dockerfile and images for CI
cilium/cilium-cli pull request #181
Opened 2021-04-21 13:47 UTC by nebril

2021-04-21 13:52 UTC, aanm requested changes

2021-04-21 13:52 UTC, aanm commented on .github/workflows/images.yaml
> +          password: ${{ secrets.QUAY_CI_PASSWORD }}
QUAY_CI_TOKEN

2021-04-21 13:52 UTC, aanm commented on Dockerfile
> +FROM busybox:stable-glibc@sha256:78089367dc288a2d7b0c40802497e8ef99c5b1536344388dd5c628f1a40abb20
`docker.io/library/busybox`

2021-04-21 13:52 UTC, aanm commented on Dockerfile
> +FROM bitnami/kubectl:1.16.15-debian-10-r220@sha256:2c35939baa0105d842f6ee144d81b083fba7b2d54f12d10025c243fa75a72a9b as kubectl
regarding `kubectl`, we can download it directly from `https://dl.k8s.io/release/${k8s_version}/bin/linux/amd64/kubectl` where `k8s_version` is something that we can provide

2021-04-21 16:57 UTC, nebril commented
The image has been built, once the review is green I will convert it to use `pull_request_target`

2021-04-23 11:07 UTC, aanm approved these changes

2021-04-23 11:43 UTC, merged