clustermesh: add support for max-connected-clusters
cilium/cilium-cli pull request #1931
Opened 2023-08-23 15:17 UTC by thorn3r

The flag 'max-connected-clusters' is a cilium-agent option that allows the user to extend the number of clusters that can be connected in a Clustermesh. This changes the maximum ClusterID that can be used, and thus cilium-cli will now validate according to the agent's configuration.

Additionally, all clusters in a Clustermesh must be configured with the same 'max-connected-clusters', and this is now validated on connection.

2023-08-28 09:42 UTC, jrajahalme requested changes
Cluster ID is used in 8-bit datapath fields, so it can not be larger than 255. So at the minimum some validation needs to be added to check that this maximum is not surpassed.

2023-08-30 13:32 UTC, derailed approved these changes
@thorn3r Nice work! LGTM.

2023-08-31 16:39 UTC, thorn3r commented
thanks @derailed !

@jrajahalme I forgot to link the associated cilium/cilium PR: https://github.com/cilium/cilium/pull/27520
TLDR: the 8-bit field can be configured to 9-bit via the new flag. This cilium-cli PR is to support configuring this flag and allow validation for `clustermesh connect` for clusters using a non-default configuration.

2023-08-31 17:16 UTC, thorn3r commented
converting this and the associated [Cilium PR](https://github.com/cilium/cilium/pull/27520) back into a draft for now until https://github.com/cilium/cilium/pull/27823 is merged. I don't anticipate any changes to the flag itself, but will hold for now

2023-09-27 18:34 UTC, thorn3r commented
putting this back into review alongside https://github.com/cilium/cilium/pull/27520

2023-10-10 07:26 UTC, jrajahalme approved these changes

2023-11-08 12:11 UTC, squeed commented
@thorn3r needs a rebase, buddy :-(

2023-11-17 09:35 UTC, merged