Changes made to connectivity/check/logging.go
cilium/cilium-cli pull request #2210
Opened 2024-01-05 19:14 UTC by AHB102

Hi there @joestringer, I forgot to add a PR, resolved issue #2042, added context as a parameter to the failCommon method, to allow each test caller to pass their own context down when invoking Fail(), Failf(), Fatal(), and Fatalf()

2024-01-05 19:32 UTC, joestringer commented
Thanks for the PR. It doesn't build, could you fix, build and test it and re-push a fresh version?

2024-01-05 19:35 UTC, AHB102 commented
I have some questions which might not be fully within the scope of this issue, so can I message you on slack ?

2024-01-05 19:54 UTC, joestringer commented
I would suggest posting in #development channel on Slack. I am not deeply involved with cilium-cli, I just noticed the issue. Posting in that public channel should provide opportunities for other developers in the community to see your messages and provide input.

2024-01-10 20:25 UTC, christarazi requested changes
Thanks for the PR. A comment below to address.

Additionally, as mentioned in the issue, please link the issue in the description of the commit msg. You can also squash the commits into one as there is no need for multiple commits here. For more info on how to format commit msgs, please see https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submit-pr.

2024-01-10 20:25 UTC, christarazi commented on connectivity/check/logging.go
> +func (t *Test) failCommon(ctx context.Context) {
This `ctx` is not used after being passed in. It seems like the `context.Background()` needs to be replaced with it on line 298.

2024-01-11 04:51 UTC, AHB102 commented
@christarazi Thanks for the comment! I'm quite new to open source, but I'm slowly but surely getting the hang of it.

2024-01-11 22:22 UTC, christarazi reviewed
Thanks!

Could you reword the title of the commit msg to be:

```
connectivity: Plumb context for SIGINT notifications
```

2024-01-11 22:22 UTC, christarazi commented on connectivity/check/logging.go
> +
Nit: extra line here that's not necessary

2024-01-12 11:44 UTC, AHB102 commented
@christarazi  I have reworded the commit message and removed the extra line at line 316.

2024-01-12 23:27 UTC, christarazi approved these changes

2024-01-12 23:28 UTC, christarazi commented
@AHB102 Seems like the code has some compilation errors.

2024-10-13 02:04 UTC, closed without merging