Add support for IPv6 in connectivity tests
cilium/cilium-cli pull request #2545
Opened 2024-05-11 23:22 UTC by lel-amri

As of today, values specified in options `--external-ip` and `--external-other-ip` are assumed to be IPv4 addresses in several places in the code. This cause some tests to fail even when a proper IPv6 configuration is specified with options `--external-cidr`, `--external-ip`, `--external-other-ip` and `--external-target`. This pull request remove the assumptions that these options holds IPv4 addresses.

2024-05-13 19:08 UTC, christarazi approved these changes

2024-05-14 11:31 UTC, doniacld commented on connectivity/tests/common.go
> +func EnsureIPv6InBackets(s string) string {
```suggestion
func EnsureIPv6InBrackets(s string) string {
```

2024-05-14 11:32 UTC, doniacld requested changes
One nit comment, otherwise LGTM 🚀

2024-06-01 17:42 UTC, lel-amri commented
Hello @christarazi and @doniacld, thanks for your review and sorry for the delay.

I'd like to write some tests to cover the new code paths but I'm unsure how to proceed. Do you have some pointers to put me on the right track?

2024-10-13 02:03 UTC, closed without merging