connectivity: Introdue Multicast connectivity test
cilium/cilium-cli pull request #2724
Opened 2024-07-25 14:26 UTC by yushoyamaguchi

Introduces Multicast connectivity test, working with netshoot container.
Using socat for IGMP and UDP communication test.
Receivers are running as Daemonset and a sender is running as a Deployment which has 1 replicaset.

Operation was confirmed on the kind and kubeadm clusters.

This if follow up of https://github.com/cilium/cilium-cli/issues/2615 .

In addtion, this PR is related to https://github.com/cilium/cilium-cli/pull/2620 .
I want to implement a test scenario using multicast subcommand discussing in above PR after this is merged.

I have the following questions and would like to discuss here and fix them.

2024-07-25 14:44 UTC, yushoyamaguchi commented
![image](https://github.com/user-attachments/assets/526e2c14-4574-4c11-8cce-ccfe44d7f89f)

This is the output of the test with `--debug`.

After rebasing the code, 
`❌ writing to junit file  failed: open : no such file or directory`
This error is occurred.

Maybe, the cause is this commit. (https://github.com/cilium/cilium-cli/commit/fa5be3a0f5563ae6f82bf47ff4d8c7339c5a4940)
The way of testing is changed or some additional setting is required?

2024-07-25 23:35 UTC, tommyp1ckles requested changes

2024-07-25 23:35 UTC, tommyp1ckles commented on connectivity/check/deployment.go
> +		/*if err := WaitForDeployment(ctx, ct, ct.clients.src, ct.Params().TestNamespace, netshootSocatClientDeploymentName); err != nil {
Unused code?

2024-07-27 03:14 UTC, yushoyamaguchi commented
In addition, maybe we have to think about it. (https://github.com/cilium/cilium-cli/pull/2724)
This multicast connectivity test is mutate cilium eBPF map temporary. (After testing, it's going back to the original state.)

2024-07-30 15:42 UTC, tommyp1ckles commented
I'll do a general code review, however multicast isn't really my area of expertise. @ldelossa Could you take a look as well?

2024-07-30 15:54 UTC, tommyp1ckles reviewed
Changes make sense to me, but I'll defer to someone who knows a bit more about Cilium multicast.

2024-07-30 15:54 UTC, tommyp1ckles commented on cli/connectivity.go
> +	cmd.Flags().StringVar(&params.NetshootImage, "netshoot-image", defaults.ConnectivityTestNetshootImage, "Image path to use for netshoot")
I know we haven't really been doing this, but could you expand the flag description to mention what this image is used for?

2024-07-30 15:54 UTC, tommyp1ckles commented on connectivity/check/deployment.go
> +		if err != nil {
Should we check if this is not ErrNotExist?

2024-07-30 15:54 UTC, tommyp1ckles commented on connectivity/check/deployment.go
> +	// Q: How about multicast deployments?
Is this leftover?

2024-07-30 15:54 UTC, tommyp1ckles commented on connectivity/tests/multicast.go
> +		if fetchdata != nil {
[errors.Join discards nil values](https://pkg.go.dev/errors#Join), so you likely don't need this nil check here.

2024-07-30 15:54 UTC, tommyp1ckles commented on connectivity/tests/multicast.go
> +					errMsg := fmt.Sprintf("Error: %v, Stderr: %s", err, stdErr.String())
minor thing, can we include the testMulticastGroupIP here, might make it easier for someone to debug issues in the future.

2024-07-30 15:54 UTC, tommyp1ckles commented on connectivity/tests/multicast.go
> +					errMsg := fmt.Sprintf("Error: %v, Stderr: %s", err, stdErr.String())
Same as above, but with mcast ip and subscriber ip.

2024-08-01 09:34 UTC, yushoyamaguchi commented
@tommyp1ckles 
Thank you for your review.
I've fixed many places which I can resolve.
I still have some questions for fix, so I'm waiting opinions of multicast expert.

P.S.
Have this discussion finished? : https://github.com/cilium/cilium-cli/pull/2726
I think whether this PR is acceptable or not depends on the outcome of that discussion.

2024-08-21 13:40 UTC, closed without merging