Flow validation fixes
cilium/cilium-cli pull request #277
Opened 2021-06-03 16:56 UTC by jrajahalme

- Only consider ICMP drops for ICMP test
- Show all matched flows on failure
- Fix DNS flow validation
- Expand flow results properly in Merge()

2021-06-07 11:13 UTC, ti-mo requested changes
Need to look into the flow matcher one of these days, but the changes look reasonable. Left some nits on the FQDN stuff.

2021-06-11 05:08 UTC, kkourt approved these changes

2021-06-11 05:47 UTC, jrajahalme commented on connectivity/check/deployment.go
> +		dep.Spec.Template.ObjectMeta.Annotations = make(map[string]string, len(p.Annotations))
Done :-)

2021-06-11 05:49 UTC, jrajahalme commented on connectivity/check/peer.go
> +	FQDN() string
I went with `FQDN` for Fully Qualified Domain Name, but if we need to drop `.cluster.local` then it will not be fully qualified any more.

2021-06-11 05:52 UTC, jrajahalme commented on connectivity/check/peer.go
> +	FQDN() string
Hostnames typically do not contain any (sub)domain parts, wondering what would be the best term for a "partially qualified domain name"?

2021-06-11 05:55 UTC, jrajahalme commented on connectivity/check/peer.go
> +	FQDN() string
Going with `DNSName()`.

2021-06-11 05:59 UTC, jrajahalme commented on connectivity/check/peer.go
> +	return strings.ReplaceAll(p.Pod.Status.PodIP, ".", "-") + "." + p.Pod.Namespace + ".pod.cluster.local"
Done.

2021-06-11 05:59 UTC, jrajahalme commented on connectivity/check/peer.go
> +	return s.Service.Name + "." + s.Service.Namespace + ".svc.cluster.local"
Done (without the `.cluster.local`)

2021-06-11 06:17 UTC, jrajahalme commented on connectivity/check/peer.go
> +	FQDN() string
We need the cluster's local domain name for DNS `qname` matching anyway, seems it is available in kubeadm-config ConfigMap.

2021-06-11 06:20 UTC, jrajahalme commented on connectivity/check/peer.go
> +	FQDN() string
Also, the returned values are not limited to the cluster, except for the pods and services within the cluster. HTTPEndpoints are not within the cluster (e.g., `www.google.com`).

2021-06-11 06:21 UTC, jrajahalme commented on connectivity/check/peer.go
> +	return strings.ReplaceAll(p.Pod.Status.PodIP, ".", "-") + "." + p.Pod.Namespace + ".pod.cluster.local"
FQDN() was used to match the _qname_ in the DNS response. Seems I'll need to read the kubeadm-config ConfigMap to get the local domain suffix.

2021-06-11 08:07 UTC, jrajahalme commented on connectivity/check/peer.go
> +	return strings.ReplaceAll(p.Pod.Status.PodIP, ".", "-") + "." + p.Pod.Namespace + ".pod.cluster.local"
Done.

2021-06-11 08:07 UTC, jrajahalme commented on connectivity/check/peer.go
> +	return s.Service.Name + "." + s.Service.Namespace + ".svc.cluster.local"
auto-detecting the local domain suffix now.

2021-06-11 08:08 UTC, jrajahalme commented on connectivity/check/peer.go
> +	return ie.host
They may have a name (which is currently always empty) returning it instead.

2021-06-11 08:08 UTC, jrajahalme commented on connectivity/check/peer.go
> +	return strings.ReplaceAll(e.workload.Status.IP, ".", "-") + "." + e.workload.Namespace + ".pod.cluster.local"
Fixed.

2021-06-11 08:10 UTC, jrajahalme commented on connectivity/check/peer.go
> +	FQDN() string
Not sure how `.cluster.local` is supposed to work with multicluster. I guess services should be fine, but maybe the synthetic pod names are only resolvable within the local cluster.

2021-06-11 08:11 UTC, jrajahalme commented
@ti-mo addressed your comments (all but one on the last commit).

2021-06-14 16:16 UTC, ti-mo requested changes

2021-06-14 16:16 UTC, ti-mo commented on connectivity/check/peer.go
> +	FQDN() string
As I mentioned above, I think we could just prefix-match DNS requests based on the TestPeer's hostname and rename this function to `Hostname()`.

2021-06-14 19:31 UTC, jrajahalme commented
@ti-mo The FQDN stuff clearly was not mature enough, so I dropped it from this series in the interest to get the more urgent fixes in.

2021-06-15 09:36 UTC, ti-mo approved these changes
Looks good, thanks! :+1:

2021-06-21 08:40 UTC, merged