Revert "workflows: fix missing CIDRs in multicluster install script"
cilium/cilium-cli pull request #302
Opened 2021-06-10 06:42 UTC by jrajahalme

This reverts commit dec9f4fd47cd27f7b40bfee7c88820908d98f61a.

Native routing CIDR in Cilium config in the multicluster setup must
cover all the clusters. Otherwise cross-cluster traffic will be
masqueraded to the source node and ingress policy enforcement in the
destination cluster will drop allowed traffic.

"10.0.0.0/9" is an educated guess that currently works. We probably
should compute the longest possible common prefix from the actual
cluster CIDRs.

Note that since the workflow trigger is `pull_request_target` this will only
take effect once merged to master. This was tested with `pull_request`
trigger prior to pushing this PR.

Fixes: #286
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

2021-06-10 15:52 UTC, nbusseneau requested changes
I see this was added originally in #194. I understand the rationale, but in that case we should fix this properly and remove the `CLUSTER_CIDR` variables from the Helm chart entirely.

I think @nebril decided to pass CIDRs to Helm because in-cluster `gcloud` CLI is not available, and this is what the CLI uses for determining cluster CIDR automatically when doing `cilium install`. So it was needed for the GKE workflow to work.

I would argue we should do either one of these:
- Fix CIDR autodetection for multicluster to work natively without needing routing tricks.
- Properly document the additional parameters required for setting up clustermesh via the CLI, since [the current docs](https://docs.cilium.io/en/v1.10/gettingstarted/clustermesh/clustermesh/) do not provide any aside from CA inheritance.

In both cases, we can then remove the `CLUSTER_CIDR_1` and `CLUSTER_CIDR_2` values from Helm.

2021-06-10 19:55 UTC, jrajahalme commented
> I would argue we should do either one of these:
> 
> * Fix CIDR autodetection for multicluster to work natively without needing routing tricks.
> * Properly document the additional parameters required for setting up clustermesh via the CLI, since [the current docs](https://docs.cilium.io/en/v1.10/gettingstarted/clustermesh/clustermesh/) do not provide any aside from CA inheritance.
> 
> In both cases, we can then remove the `CLUSTER_CIDR_1` and `CLUSTER_CIDR_2` values from Helm.

Doc changes: https://github.com/cilium/cilium/pull/16499.

Pushed commit to remove the unused Helm values.

Will remove the last commit once the test succeeds.

2021-06-10 20:16 UTC, pchaigno approved these changes
LGTM assuming the third commit is removed of course.

2021-06-10 20:36 UTC, jrajahalme commented
> LGTM assuming the third commit is removed of course.

3rd commit removed :-)

2021-06-10 20:38 UTC, pchaigno commented
And the test had passed: https://github.com/cilium/cilium-cli/actions/runs/926321915 :tada: :ship:

2021-06-10 21:42 UTC, nbusseneau approved these changes
Thanks LGTM.

Small nit, if you'd like to fix:
- Remove `step.id` on lines 57 and 80 `.github/workflows/multicluster.yaml` since they are now unused.

2021-06-10 21:43 UTC, nbusseneau commented
Do you think it is worth creating an issue to track CIDR autodetection on CLI side for multicluster?

2021-06-11 05:34 UTC, jrajahalme commented
> Do you think it is worth creating an issue to track CIDR autodetection on CLI side for multicluster?

Yes, it would be better if native-routing-cidr could be autodetected. Not sure if it can be done before `cilium clustermesh connect`, but at that time we could reconfigure both ends if the other cluster's CIDR is not covered by the current native routing CIDR. Unless tunneling is on, that is.

2021-06-11 05:36 UTC, jrajahalme commented
> * Remove `step.id` on lines 57 and 80 `.github/workflows/multicluster.yaml` since they are now unused.

Removed :-)

2021-06-11 12:44 UTC, merged