workflows: fix in-cluster job kubectl wait
cilium/cilium-cli pull request #451
Opened 2021-07-21 18:48 UTC by nbusseneau

2021-07-21 20:56 UTC, nbusseneau commented
Links to test runs of workflow changes:
- EKS: https://github.com/cilium/cilium-cli/actions/runs/1053975796
- EKS (tunnel): https://github.com/cilium/cilium-cli/actions/runs/1053975803
- GKE: https://github.com/cilium/cilium-cli/actions/runs/1053975793
- Multicluster: https://github.com/cilium/cilium-cli/actions/runs/1053975794
- External workloads: https://github.com/cilium/cilium-cli/actions/runs/1053975802

2021-07-21 21:09 UTC, michi-covalent approved these changes

2021-07-21 22:54 UTC, christarazi approved these changes
Nice find

2021-07-22 08:09 UTC, nbusseneau commented
All test runs passed except EKS (tunnel), but that is because of the consistent failure discussed on Slack [here](https://cilium.slack.com/archives/C7PE7V806/p1626877817422600?thread_ts=1626877621.422500&cid=C7PE7V806).

Since:
- The changes in this PR have been validated against other workflows and are exactly the same in EKS (tunnel).
- The PR improves CI testing on `cilium-cli` (faster runs).
- The PR will help to debug the EKS (tunnel) issue itself, since the workflow is now more reliable and does not hit the "hard job timeout" (as seen in other runs of the workflow) which causes unreliable information gathering / cluster cleanup.
=> We are in one of the exception cases to the zero-flakes strategy and do not need to wait to rebase on top of the future (hopefully soon) fix for the EKS (tunnel) workflow.

This PR can be marked as `ready-to-merge` once reviews are in.

2021-07-22 14:06 UTC, aanm requested changes
Needs similar changes in the *-v1.10 GH workflows

2021-07-22 14:37 UTC, nbusseneau commented
> Needs similar changes in the *-v1.10 GH workflows
Sir, this is `cilium-cli`. We don't do that here.

2021-07-22 15:41 UTC, aanm approved these changes

2021-07-22 17:29 UTC, merged