Retry GCP VM creation
cilium/cilium-cli pull request #463
Opened 2021-08-04 20:46 UTC by michi-covalent

Fixes #445

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

2021-08-04 22:36 UTC, christarazi approved these changes

2021-08-04 22:36 UTC, christarazi commented on .github/workflows/externalworkloads.yaml
> +          max_attempts: 3
Nice, fancy stuff.

2021-08-05 13:58 UTC, nbusseneau requested changes
Thanks, some comments below :)

2021-08-05 13:58 UTC, nbusseneau commented on .github/workflows/externalworkloads.yaml
> +        uses: nick-invision/retry@v2
We should pin this GH Action to a SHA for better control over the dependency:
```suggestion
        uses: nick-invision/retry@45ba062d357edb3b29c4a94b456b188716f61020
```

2021-08-05 13:58 UTC, nbusseneau commented on .github/workflows/externalworkloads.yaml
> +          timeout_minutes: 1
Would suggest simply retrying on error rather than on timeout:
```suggestion
          retry_on: error
```

2021-08-05 15:16 UTC, michi-covalent commented
@nbusseneau thanks for your feedback. updated the pr 🚀

2021-08-05 15:32 UTC, nbusseneau approved these changes
🚀

2021-08-05 18:17 UTC, michi-covalent commented
quay timeout. restarting.

> docker: Error response from daemon: Head "https://quay.io/v2/cilium/cilium/manifests/v1.10.3": Get "https://quay.io/v2/auth?scope=repository%3Acilium%2Fcilium%3Apull&service=quay.io": net/http: TLS handshake timeout.

2021-08-05 20:31 UTC, michi-covalent commented
i'll delete https://github.com/cilium/cilium-cli/pull/463/commits/e88e8fedfdac246d72cc32df05cf95417660289a and then merge.

2021-08-05 20:33 UTC, merged