use `default/kubernetes` to test for dns
cilium/cilium-cli pull request #479
Opened 2021-08-11 16:07 UTC by zhaojizhuang

fix #464 
use `default/kubernetes` to test for dns

Signed-off-by: zhaojizhuang <571130360@qq.com>

2021-08-11 16:07 UTC, zhaojizhuang commented
/assign @twpayne @gandro

2021-08-11 16:19 UTC, gandro commented
The test failures look legitimate:
```
server can't find kubernetes.default: NXDOMAIN
```

2021-08-12 06:05 UTC, zhaojizhuang commented
/retest

2021-08-12 07:20 UTC, zhaojizhuang commented
cc @gandro

2021-08-12 08:29 UTC, tklauser requested changes
@zhaojizhuang please squash the commits of this PR into one and add a commit message describing the intent of the change.

2021-08-12 08:34 UTC, zhaojizhuang commented
> @zhaojizhuang please squash the commits of this PR into one and add a commit message describing the intent of the change.

@tklauser Done

2021-08-12 08:36 UTC, gandro requested changes
Thanks for the revision. I left an inline comment why this new approach however will not work. Overall, the previous approach of using `nslookup kubernetes.default` was the correct one, as it will rely on `nslookup` doing the /etc/resolv.conf parsing for us.

The problem seems to be that our client docker image ships with `busybox` nslookup, which is known to be broken: https://github.com/kubernetes/kubernetes/issues/66924

I did a quick test locally, and if I install the upstream `nslookup` from bind-tools in the container, then `nslookup kubernetes.default` succeeds. My proposal therefore is to do the following:

1. Install the proper (non-busybox) version of `nslookup` from bind-tools in the images used for the connectivity test. We can add `bind-tools` here:
https://github.com/cilium/alpine-curl/blob/bcb227dc6431447fce30bfa8f80ebb1442729eb3/Dockerfile#L13
2. Release a new version of the `alpine-curl` image (I can help you with that) such that it contains a correct version of `nslookup`
3. Revert this to the previous approach of just invoking `nslookup kubernetes.default`, with the proper `nslookup` version, it will then actually do the right thing and parse the `/etc/resolv.conf` for you.

What do you think?

2021-08-12 09:04 UTC, zhaojizhuang commented on connectivity/check/util.go
> +		f, err := os.Open(resolverFileName)
@gandro For Pod running in the k8s cluster, it's `/etc/resolv.conf` if generated according to the `{{ .DNSDomain }}` https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L162 

Then we get the clusterdomain by this function `GetClusterDomainName `

for cluster 
```bash
    .:53 {
        errors
        health
        ready
        kubernetes example-cluster in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
```

and the `/etc/resolv.conf` in pod is 
```bash
/ # cat /etc/resolv.conf
nameserver 169.254.25.10
search testnamespace.svc.example-cluster. svc.example-cluster. example-cluster.
options ndots:5
```
certainly we can fix the alpine image

2021-08-12 09:25 UTC, zhaojizhuang commented on connectivity/check/util.go
> +		f, err := os.Open(resolverFileName)
@gandro https://github.com/cilium/alpine-curl/pull/14

2021-08-12 09:47 UTC, tklauser requested changes
A a new version v1.4.0 of the `alpine-curl` image was released with the fix. So will also need to update to that new version here once the corresponding image is built and pushed to quay.io:

https://github.com/cilium/cilium-cli/blob/254a814c6603c3ea22d63c14b83be69c4735f098/defaults/defaults.go#L75

2021-08-12 10:01 UTC, gandro approved these changes

2021-08-12 12:25 UTC, tklauser approved these changes

2021-08-12 12:59 UTC, merged