envoy crd / ingress controller support
cilium/cilium-cli pull request #643
Opened 2021-12-06 08:11 UTC by michi-covalent

3 commits:

- add ciliumegressnatpolicy and ciliumenvoyconfig to cluster role.
- update cluster role for ingress controller
- create cilium ingress class.

2021-12-06 09:14 UTC, jrajahalme approved these changes

2021-12-06 09:20 UTC, tklauser requested changes
Two small nits, otherwise LGTM.

2021-12-06 09:20 UTC, tklauser commented on internal/k8s/helpers.go
> +}
Let's change the ingress controller name to be passed as an argument, akin to other functions in this package:

```suggestion
func NewIngressClass(name, controllerName string) *v1.IngressClass {
	return &v1.IngressClass{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Spec: v1.IngressClassSpec{
			Controller: controllerName,
		},
	}
}
```

2021-12-06 09:20 UTC, tklauser commented on internal/k8s/helpers.go
> +	v1 "k8s.io/api/networking/v1"
```suggestion
	networkingv1 "k8s.io/api/networking/v1"
```

2021-12-06 10:16 UTC, tklauser approved these changes

2021-12-06 10:25 UTC, michi-covalent commented
aks failed to pull quay.io/cilium/cilium-cli-ci:313536d43e475cac9bcabd155e26f67d2d3dfd20. i can pull it now, so i think it's a transient failure. restarting.

2021-12-06 10:30 UTC, twpayne approved these changes

2021-12-06 20:43 UTC, christarazi approved these changes

2021-12-08 04:50 UTC, michi-covalent commented
https://github.com/cilium/cilium-cli/runs/4451759861?check_suite_focus=true

failed to download eksctl. restarting!

2021-12-08 10:34 UTC, merged