Add host networking scenario for performance tests
cilium/cilium-cli pull request #816
Opened 2022-04-27 16:48 UTC by learnitall

Adds a new CLI argument `--host-net` to the `--perf` test suite, which acts a toggle for choosing whether or not pods are deployed into the node's network namespace. This involves leveraging the `HostNetwork` option in the pod spec.

The goal of this change is to allow us to run a host networking scenario performance test.

2022-04-27 19:29 UTC, michi-covalent approved these changes

2022-04-27 19:29 UTC, michi-covalent commented
@jtaleric could you also take a look? 🙏

2022-04-27 20:13 UTC, jtaleric requested changes
Instead of modifying the current Deployments, lets create net-new deployments with descriptive names -- PerfClientHostNet for example. 

Reason being, user runs `cilium connectivity test --perf` initially, if they then run, with `--host-net` the deployments are not cleaned up, unless the user deletes the `cilium-test` namespace -- the test will continue to run without hostNetwork.

2022-04-27 20:16 UTC, jtaleric commented
One additional thought, we should add some sort of description to the scenario to the result output.  Maybe add to the `PerfResult struct` a Scenario string, which we just update based on the test that is ran? 

```
🔥 Performance Test Summary
-----------------------------------------------------------------------------------------------------------------------------
📋 Scenario                                           | Test            | Num Samples     | Duration        | Avg value      
-----------------------------------------------------------------------------------------------------------------------------
📋 perf-client-other-node-6b9b76bc7b-9vb5c            | TCP_RR          | 1               | 10s             | 8473.78 (OP/s)
📋 perf-client-other-node-6b9b76bc7b-9vb5c            | TCP_STREAM      | 1               | 10s             | 1897.42 (Mb/s)
📋 perf-client-other-node-6b9b76bc7b-9vb5c            | UDP_RR          | 1               | 10s             | 8085.05 (OP/s)
📋 perf-client-other-node-6b9b76bc7b-9vb5c            | UDP_STREAM      | 1               | 10s             | 1495.08 (Mb/s)
📋 perf-client-74b856b479-6dtn4                       | TCP_RR          | 1               | 10s             | 35272.07 (OP/s)
📋 perf-client-74b856b479-6dtn4                       | TCP_STREAM      | 1               | 10s             | 4541.65 (Mb/s)
📋 perf-client-74b856b479-6dtn4                       | UDP_RR          | 1               | 10s             | 37335.39 (OP/s)
📋 perf-client-74b856b479-6dtn4                       | UDP_STREAM      | 1               | 10s             | 779.05 (Mb/s)
-----------------------------------------------------------------------------------------------------------------------------

```

2022-04-28 21:04 UTC, learnitall commented
@jtaleric Makes a ton of sense, I'll get onto changing the deployment names and adding a scenario description in the output.

2022-05-02 23:55 UTC, learnitall commented
@jtaleric Deployments for host networking now have a `--host-net` suffix. I also added the scenario to the testing output. Here's what it looks like without `--host-net`:

```
🔥 Performance Test Summary:
-------------------------------------------------------------------------------------------------------------------------------------------------
📋 Scenario        | Pod                                                | Test            | Num Samples     | Duration        | Avg value
-------------------------------------------------------------------------------------------------------------------------------------------------
📋 pod-net         | perf-client-668f667cd5-jnjlg                       | UDP_STREAM      | 1               | 1s              | 3042.86 (Mb/s)
📋 pod-net         | perf-client-other-node-5699666544-ggctx            | TCP_RR          | 1               | 1s              | 31233.07 (OP/s)
📋 pod-net         | perf-client-other-node-5699666544-ggctx            | TCP_STREAM      | 1               | 1s              | 941.71 (Mb/s)
📋 pod-net         | perf-client-other-node-5699666544-ggctx            | UDP_RR          | 1               | 1s              | 32825.67 (OP/s)
📋 pod-net         | perf-client-other-node-5699666544-ggctx            | UDP_STREAM      | 1               | 1s              | 779.30 (Mb/s)
📋 pod-net         | perf-client-668f667cd5-jnjlg                       | TCP_RR          | 1               | 1s              | 84521.07 (OP/s)
📋 pod-net         | perf-client-668f667cd5-jnjlg                       | TCP_STREAM      | 1               | 1s              | 3156.26 (Mb/s)
📋 pod-net         | perf-client-668f667cd5-jnjlg                       | UDP_RR          | 1               | 1s              | 56798.58 (OP/s)
-------------------------------------------------------------------------------------------------------------------------------------------------
```

And with:

```
[=] Test [network-perf]
..
🔥 Performance Test Summary:
-------------------------------------------------------------------------------------------------------------------------------------------------
📋 Scenario        | Pod                                                | Test            | Num Samples     | Duration        | Avg value
-------------------------------------------------------------------------------------------------------------------------------------------------
📋 host-net        | perf-client-other-node-host-net-79ddb9d859-bnsj4   | TCP_RR          | 1               | 1s              | 33445.85 (OP/s)
📋 host-net        | perf-client-other-node-host-net-79ddb9d859-bnsj4   | TCP_STREAM      | 1               | 1s              | 715.11 (Mb/s)
📋 host-net        | perf-client-other-node-host-net-79ddb9d859-bnsj4   | UDP_RR          | 1               | 1s              | 40749.76 (OP/s)
📋 host-net        | perf-client-other-node-host-net-79ddb9d859-bnsj4   | UDP_STREAM      | 1               | 1s              | 1207.97 (Mb/s)
📋 host-net        | perf-client-host-net-5fbcdd79d7-vwnwm              | TCP_RR          | 1               | 1s              | 35206.49 (OP/s)
📋 host-net        | perf-client-host-net-5fbcdd79d7-vwnwm              | TCP_STREAM      | 1               | 1s              | 10131.97 (Mb/s)
📋 host-net        | perf-client-host-net-5fbcdd79d7-vwnwm              | UDP_RR          | 1               | 1s              | 53116.49 (OP/s)
📋 host-net        | perf-client-host-net-5fbcdd79d7-vwnwm              | UDP_STREAM      | 1               | 1s              | 1900.73 (Mb/s)
-------------------------------------------------------------------------------------------------------------------------------------------------
```

2022-05-05 18:31 UTC, jtaleric approved these changes
LGTM @learnitall Thanks! 

✅  Tested locally

Great work!

2022-05-05 18:35 UTC, merged