clustermesh: Update cluster-name/cluster-id validation message
cilium/cilium-cli pull request #948
Opened 2022-06-24 14:33 UTC by sayboras

This commit is to make the message clearer if default values are used.
Reported by cilium user in slack channel.

Suggested-by: André Martins <andre@cilium.io>
Signed-off-by: Tam Mach <tam.mach@cilium.io>

2022-06-24 14:34 UTC, aanm requested changes

2022-06-24 14:34 UTC, aanm commented on clustermesh/clustermesh.go
> +		return fmt.Errorf("local cluster has non-unique name (cluster-name: %s) and/or ID (cluster-id: %s)", aiLocal.ClusterName, aiLocal.ClusterID)
`s+and/or ID+and/or ID 0+`

2022-06-27 12:59 UTC, tklauser approved these changes

2022-06-27 14:33 UTC, aanm approved these changes

2022-06-27 15:36 UTC, merged