connectivity: Add -t to prefix log msg with timestamp
cilium/cilium-cli pull request #981
Opened 2022-07-19 12:05 UTC by brb

This will help us to correlate cmd execution with hubble flows (e.g., when debugging the Conformance GKE flake).

2022-07-19 12:19 UTC, tklauser reviewed
Could we make this not specific to just debug logs but add it in a more generic way where we could use a CLI flag to enable/disable log timestamps for all log messages regardless of log level?

2022-07-21 06:21 UTC, brb commented
> Could we make this not specific to just debug logs but add it in a more generic way where we could use a CLI flag to enable/disable log timestamps for all log messages regardless of log level?

Good idea, let me take a stab at it.

2022-07-21 11:35 UTC, tklauser requested changes
Looks like this does not yet work correctly for info and warn messages in non-debug mode:

```
% cilium connectivity test -t
ℹ️  Monitor aggregation detected, will skip some flow validation steps
[2022-07-21T13:28:21+02:00]✨ [kind-kind] Creating namespace cilium-test for connectivity check...
[2022-07-21T13:28:21+02:00]✨ [kind-kind] Deploying echo-same-node service...
[2022-07-21T13:28:21+02:00]✨ [kind-kind] Deploying DNS test server configmap...
[2022-07-21T13:28:21+02:00]✨ [kind-kind] Deploying same-node deployment...
[2022-07-21T13:28:21+02:00]✨ [kind-kind] Deploying client deployment...
[2022-07-21T13:28:21+02:00]✨ [kind-kind] Deploying client2 deployment...
[2022-07-21T13:28:21+02:00]✨ [kind-kind] Deploying echo-other-node service...
[2022-07-21T13:28:21+02:00]✨ [kind-kind] Deploying other-node deployment...
[2022-07-21T13:28:21+02:00]⌛ [kind-kind] Waiting for deployments [client client2 echo-same-node] to become ready...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for deployments [echo-other-node] to become ready...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/client-7df6cfbf7b-m2wvr to appear...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/client2-547996d7d8-9lwq6 to appear...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for pod cilium-test/client-7df6cfbf7b-m2wvr to reach DNS server on cilium-test/echo-same-node-7c4b55f976-s58m5 pod...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for pod cilium-test/client2-547996d7d8-9lwq6 to reach DNS server on cilium-test/echo-same-node-7c4b55f976-s58m5 pod...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for pod cilium-test/client-7df6cfbf7b-m2wvr to reach DNS server on cilium-test/echo-other-node-8ff6c9f5f-d5wkb pod...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for pod cilium-test/client2-547996d7d8-9lwq6 to reach DNS server on cilium-test/echo-other-node-8ff6c9f5f-d5wkb pod...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for pod cilium-test/client-7df6cfbf7b-m2wvr to reach default/kubernetes service...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for pod cilium-test/client2-547996d7d8-9lwq6 to reach default/kubernetes service...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-8ff6c9f5f-d5wkb to appear...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-7c4b55f976-s58m5 to appear...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for Service cilium-test/echo-other-node to become ready...
[2022-07-21T13:28:41+02:00]⌛ [kind-kind] Waiting for Service cilium-test/echo-same-node to become ready...
[2022-07-21T13:28:42+02:00]⌛ [kind-kind] Waiting for NodePort 172.19.0.3:30348 (cilium-test/echo-other-node) to become ready...
[2022-07-21T13:28:42+02:00]⌛ [kind-kind] Waiting for NodePort 172.19.0.3:30356 (cilium-test/echo-same-node) to become ready...
[2022-07-21T13:28:42+02:00]⌛ [kind-kind] Waiting for NodePort 172.19.0.2:30348 (cilium-test/echo-other-node) to become ready...
[2022-07-21T13:28:42+02:00]⌛ [kind-kind] Waiting for NodePort 172.19.0.2:30356 (cilium-test/echo-same-node) to become ready...
[2022-07-21T13:28:42+02:00]⌛ [kind-kind] Waiting for NodePort 172.19.0.4:30348 (cilium-test/echo-other-node) to become ready...
[2022-07-21T13:28:42+02:00]⌛ [kind-kind] Waiting for NodePort 172.19.0.4:30356 (cilium-test/echo-same-node) to become ready...
ℹ️  [2022-07-21T13:28:42+02:00]Skipping IPCache check
[2022-07-21T13:28:42+02:00]🔭 Enabling Hubble telescope...
⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4245: connect: connection refused"
ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium hubble port-forward&
ℹ️  [2022-07-21T13:28:42+02:00]Cilium version: 1.12.0
[2022-07-21T13:28:42+02:00]🏃 Running tests...
[2022-07-21T13:28:42+02:00]
[2022-07-21T13:28:42+02:00][=] Test [no-policies]
....................................[2022-07-21T13:28:47+02:00]
[2022-07-21T13:28:47+02:00][=] Test [allow-all-except-world]
..............[2022-07-21T13:28:49+02:00]
[2022-07-21T13:28:49+02:00][=] Test [client-ingress]
..[2022-07-21T13:28:54+02:00]
[2022-07-21T13:28:54+02:00][=] Test [echo-ingress]
....[2022-07-21T13:29:06+02:00]
[2022-07-21T13:29:06+02:00][=] Test [client-egress]
....[2022-07-21T13:29:08+02:00]
[2022-07-21T13:29:08+02:00][=] Test [to-entities-world]
......[2022-07-21T13:29:26+02:00]
[2022-07-21T13:29:26+02:00][=] Test [to-cidr-1111]
....[2022-07-21T13:29:38+02:00]
[2022-07-21T13:29:38+02:00][=] Test [echo-ingress-l7]
............[2022-07-21T13:30:11+02:00]
[2022-07-21T13:30:11+02:00][=] Test [client-egress-l7]
..........[2022-07-21T13:30:43+02:00]
[2022-07-21T13:30:43+02:00][=] Test [dns-only]
..........[2022-07-21T13:31:29+02:00]
[2022-07-21T13:31:29+02:00][=] Test [to-fqdns]
......
✅ All 11 tests (108 actions) successful, 0 tests skipped, 0 scenarios skipped.
```

Probably writing of the timestamp needs to be moved out of `(*ConnectivityTest).[Ll]og{,f}` into `(*ConnectivityTest).(Info|Warn|Fail|Fatal){,f}`.

2022-07-21 11:35 UTC, tklauser commented on connectivity/check/logging.go
> +	return fmt.Sprintf("[%s]", time.Now().Format(time.RFC3339))
Nit: I'd add an additional space after the timestamp

```suggestion
	return fmt.Sprintf("[%s] ", time.Now().Format(time.RFC3339))
```

2022-07-26 09:08 UTC, jrajahalme approved these changes
Suggest adding the space as proposed by @tklauser

2022-08-03 08:20 UTC, brb commented
> Looks like this does not yet work correctly for info and warn messages in non-debug mode:

@tklauser Thanks for catching this, and sorry for the delay :grimacing: . I am thinking about consolidating `ct.Warn|Info|Debug` with `ct.Log` in a way that the former won't invoke the latter, i.e. it will directly write to `ct.params.Writer`. Does this make sense to you?

2022-08-03 09:07 UTC, tklauser commented
> > Looks like this does not yet work correctly for info and warn messages in non-debug mode:
> 
> @tklauser Thanks for catching this, and sorry for the delay grimacing . I am thinking about consolidating `ct.Warn|Info|Debug` with `ct.Log` in a way that the former won't invoke the latter, i.e. it will directly write to `ct.params.Writer`. Does this make sense to you?

:+1: this sounds like a good approach to me.

2022-08-03 11:13 UTC, brb commented
It looks much better now:
```
> ./cilium connectivity test -d -v -t
[2022-08-03T13:08:25+02:00] 🐛 Detected features:
[2022-08-03T13:08:25+02:00] 🐛   cni-chaining: Enabled:none
[2022-08-03T13:08:25+02:00] 🐛   host-firewall: Disabled
[2022-08-03T13:08:25+02:00] 🐛   l7-proxy: Enabled
[2022-08-03T13:08:25+02:00] 🐛   monitor-aggregation: Enabled:medium
[2022-08-03T13:08:25+02:00] ℹ️  Monitor aggregation detected, will skip some flow validation steps
[2022-08-03T13:08:25+02:00] ✨ [kind-kind] Creating namespace cilium-test for connectivity check...
[2022-08-03T13:08:25+02:00] ✨ [kind-kind] Deploying echo-same-node service...
[2022-08-03T13:08:26+02:00] ✨ [kind-kind] Deploying DNS test server configmap...
[2022-08-03T13:08:26+02:00] ✨ [kind-kind] Deploying same-node deployment...
[2022-08-03T13:08:26+02:00] ✨ [kind-kind] Deploying client deployment...
[2022-08-03T13:08:26+02:00] ✨ [kind-kind] Deploying client2 deployment...
[2022-08-03T13:08:26+02:00] ✨ [kind-kind] Deploying echo-other-node service...
[2022-08-03T13:08:26+02:00] ✨ [kind-kind] Deploying other-node deployment...
[2022-08-03T13:08:26+02:00] 🐛 Validating Deployments...
[2022-08-03T13:08:26+02:00] ⌛ [kind-kind] Waiting for deployments [client client2 echo-same-node] to become ready...
[2022-08-03T13:09:26+02:00] ⌛ [kind-kind] Waiting for deployments [echo-other-node] to become ready...
[2022-08-03T13:09:30+02:00] ⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/client-7df6cfbf7b-cq4v9 to appear...
[2022-08-03T13:09:30+02:00] ⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/client2-547996d7d8-fvn6n to appear...
[2022-08-03T13:09:30+02:00] ⌛ [kind-kind] Waiting for pod cilium-test/client-7df6cfbf7b-cq4v9 to reach DNS server on cilium-test/echo-same-node-7c4b55f976-wc4c9 pod...
[2022-08-03T13:09:30+02:00] ⌛ [kind-kind] Waiting for pod cilium-test/client2-547996d7d8-fvn6n to reach DNS server on cilium-test/echo-same-node-7c4b55f976-wc4c9 pod...
[2022-08-03T13:09:30+02:00] ⌛ [kind-kind] Waiting for pod cilium-test/client2-547996d7d8-fvn6n to reach DNS server on cilium-test/echo-other-node-8ff6c9f5f-vtwrw pod...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for pod cilium-test/client-7df6cfbf7b-cq4v9 to reach DNS server on cilium-test/echo-other-node-8ff6c9f5f-vtwrw pod...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for pod cilium-test/client-7df6cfbf7b-cq4v9 to reach default/kubernetes service...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for pod cilium-test/client2-547996d7d8-fvn6n to reach default/kubernetes service...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-8ff6c9f5f-vtwrw to appear...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-7c4b55f976-wc4c9 to appear...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for Service cilium-test/echo-other-node to become ready...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for Service cilium-test/echo-same-node to become ready...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for NodePort 172.18.0.4:31040 (cilium-test/echo-other-node) to become ready...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for NodePort 172.18.0.4:31036 (cilium-test/echo-same-node) to become ready...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for NodePort 172.18.0.5:31040 (cilium-test/echo-other-node) to become ready...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for NodePort 172.18.0.5:31036 (cilium-test/echo-same-node) to become ready...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for NodePort 172.18.0.3:31040 (cilium-test/echo-other-node) to become ready...
[2022-08-03T13:09:31+02:00] ⌛ [kind-kind] Waiting for NodePort 172.18.0.3:31036 (cilium-test/echo-same-node) to become ready...
[2022-08-03T13:09:31+02:00] ℹ️  Skipping IPCache check
[2022-08-03T13:09:31+02:00] 🔭 Enabling Hubble telescope...
[2022-08-03T13:09:31+02:00] ⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:4245: connect: connection refused"
[2022-08-03T13:09:31+02:00] ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium hubble port-forward&
[2022-08-03T13:09:32+02:00] ⚠️  Unable to detect Cilium version, assuming v1.12.0 for connectivity tests: unable to parse cilium version on pod "cilium-grhw5": Invalid character(s) found in patch number "0\n"
[2022-08-03T13:09:32+02:00] ℹ️  Cilium version: 1.12.0
[2022-08-03T13:09:32+02:00] 🐛 Registered connectivity tests:
[2022-08-03T13:09:32+02:00] 🐛   <Test no-policies, 9 scenarios, 0 CNPs, expectFunc <nil>>
[2022-08-03T13:09:32+02:00] 🐛   <Test allow-all-except-world, 5 scenarios, 1 CNPs, expectFunc <nil>>
[2022-08-03T13:09:32+02:00] 🐛   <Test client-ingress, 1 scenarios, 1 CNPs, expectFunc 0x1c0c080>
[2022-08-03T13:09:32+02:00] 🐛   <Test echo-ingress, 1 scenarios, 1 CNPs, expectFunc 0x1c0c2a0>
[2022-08-03T13:09:32+02:00] 🐛   <Test client-egress, 1 scenarios, 1 CNPs, expectFunc <nil>>
[2022-08-03T13:09:32+02:00] 🐛   <Test to-entities-world, 1 scenarios, 1 CNPs, expectFunc 0x1c0c500>
[2022-08-03T13:09:32+02:00] 🐛   <Test to-cidr-1111, 1 scenarios, 1 CNPs, expectFunc 0x1c0c660>
[2022-08-03T13:09:32+02:00] 🐛   <Test echo-ingress-l7, 1 scenarios, 1 CNPs, expectFunc 0x1c0c7e0>
[2022-08-03T13:09:32+02:00] 🐛   <Test client-egress-l7, 2 scenarios, 2 CNPs, expectFunc 0x1c0cb40>
[2022-08-03T13:09:32+02:00] 🐛   <Test dns-only, 2 scenarios, 1 CNPs, expectFunc 0x1c0cf00>
[2022-08-03T13:09:32+02:00] 🐛   <Test to-fqdns, 1 scenarios, 1 CNPs, expectFunc 0x1c0cfa0>
[2022-08-03T13:09:32+02:00] 🏃 Running tests...
[2022-08-03T13:09:32+02:00]
[2022-08-03T13:09:32+02:00] [=] Test [no-policies]
[2022-08-03T13:09:32+02:00]   [-] Scenario [no-policies/pod-to-local-nodeport]
[2022-08-03T13:09:32+02:00]   [.] Action [no-policies/pod-to-local-nodeport/curl-0: cilium-test/client-7df6cfbf7b-cq4v9 (10.244.2.159) -> cilium-test/echo-same-node (echo-same-node:8080)]
[2022-08-03T13:09:32+02:00]   🐛 Executing command [curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://172.18.0.3:31036]
[2022-08-03T13:09:32+02:00]   [.] Action [no-policies/pod-to-local-nodeport/curl-1: cilium-test/client-7df6cfbf7b-cq4v9 (10.244.2.159) -> cilium-test/echo-other-node (echo-other-node:8080)]
[2022-08-03T13:09:32+02:00]   🐛 Executing command [curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://172.18.0.3:31040]
[2022-08-03T13:09:32+02:00]   [.] Action [no-policies/pod-to-local-nodeport/curl-2: cilium-test/client2-547996d7d8-fvn6n (10.244.2.71) -> cilium-test/echo-other-node (echo-other-node:8080)]
[2022-08-03T13:09:32+02:00]   🐛 Executing command [curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://172.18.0.3:31040]
[2022-08-03T13:09:32+02:00]   [.] Action [no-policies/pod-to-local-nodeport/curl-3: cilium-test/client2-547996d7d8-fvn6n (10.244.2.71) -> cilium-test/echo-same-node (echo-same-node:8080)]
[2022-08-03T13:09:32+02:00]   🐛 Executing command [curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://172.18.0.3:31036]
[2022-08-03T13:09:32+02:00]   [-] Scenario [no-policies/pod-to-world]
[2022-08-03T13:09:32+02:00]   [.] Action [no-policies/pod-to-world/http-to-one-one-one-one-0: cilium-test/client-7df6cfbf7b-cq4v9 (10.244.2.159) -> one-one-one-one-http (one.one.one.one:80)]
[2022-08-03T13:09:32+02:00]   🐛 Executing command [curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /de [...]

2022-08-03 12:20 UTC, tklauser approved these changes
Nice, thanks!

2022-08-03 12:20 UTC, merged